# Generated by Django 4.2.2 on 2023-06-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_tickets_per_user",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
